package modelo;
// Generated 12/12/2018 16:48:23 by Hibernate Tools 4.3.1



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String nombreEstado;
     private String observacionesEstado;

    public Estado() {
    }

    public Estado(String nombreEstado, String observacionesEstado) {
       this.nombreEstado = nombreEstado;
       this.observacionesEstado = observacionesEstado;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public String getObservacionesEstado() {
        return this.observacionesEstado;
    }
    
    public void setObservacionesEstado(String observacionesEstado) {
        this.observacionesEstado = observacionesEstado;
    }




}


